/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as CompetitionsCompetitionIdIndexRouteImport } from './routes/competitions/$competitionId/index'
import { Route as CompetitionsCompetitionIdLeaderboardRouteImport } from './routes/competitions/$competitionId/leaderboard'
import { Route as ApiCronScoreRouteImport } from './routes/api/cron/score'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CompetitionsCompetitionIdMatchesIndexRouteImport } from './routes/competitions/$competitionId/matches/index'
import { Route as CompetitionsCompetitionIdLeaguesIndexRouteImport } from './routes/competitions/$competitionId/leagues/index'
import { Route as CompetitionsCompetitionIdLeaguesJoinRouteImport } from './routes/competitions/$competitionId/leagues/join'
import { Route as CompetitionsCompetitionIdLeaguesLeagueIdRouteImport } from './routes/competitions/$competitionId/leagues/$leagueId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdIndexRoute =
  CompetitionsCompetitionIdIndexRouteImport.update({
    id: '/competitions/$competitionId/',
    path: '/competitions/$competitionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetitionsCompetitionIdLeaderboardRoute =
  CompetitionsCompetitionIdLeaderboardRouteImport.update({
    id: '/competitions/$competitionId/leaderboard',
    path: '/competitions/$competitionId/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronScoreRoute = ApiCronScoreRouteImport.update({
  id: '/api/cron/score',
  path: '/api/cron/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdMatchesIndexRoute =
  CompetitionsCompetitionIdMatchesIndexRouteImport.update({
    id: '/competitions/$competitionId/matches/',
    path: '/competitions/$competitionId/matches/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetitionsCompetitionIdLeaguesIndexRoute =
  CompetitionsCompetitionIdLeaguesIndexRouteImport.update({
    id: '/competitions/$competitionId/leagues/',
    path: '/competitions/$competitionId/leagues/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetitionsCompetitionIdLeaguesJoinRoute =
  CompetitionsCompetitionIdLeaguesJoinRouteImport.update({
    id: '/competitions/$competitionId/leagues/join',
    path: '/competitions/$competitionId/leagues/join',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetitionsCompetitionIdLeaguesLeagueIdRoute =
  CompetitionsCompetitionIdLeaguesLeagueIdRouteImport.update({
    id: '/competitions/$competitionId/leagues/$leagueId',
    path: '/competitions/$competitionId/leagues/$leagueId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
  '/competitions/$competitionId/leaderboard': typeof CompetitionsCompetitionIdLeaderboardRoute
  '/competitions/$competitionId/': typeof CompetitionsCompetitionIdIndexRoute
  '/competitions/$competitionId/leagues/$leagueId': typeof CompetitionsCompetitionIdLeaguesLeagueIdRoute
  '/competitions/$competitionId/leagues/join': typeof CompetitionsCompetitionIdLeaguesJoinRoute
  '/competitions/$competitionId/leagues/': typeof CompetitionsCompetitionIdLeaguesIndexRoute
  '/competitions/$competitionId/matches/': typeof CompetitionsCompetitionIdMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
  '/competitions/$competitionId/leaderboard': typeof CompetitionsCompetitionIdLeaderboardRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdIndexRoute
  '/competitions/$competitionId/leagues/$leagueId': typeof CompetitionsCompetitionIdLeaguesLeagueIdRoute
  '/competitions/$competitionId/leagues/join': typeof CompetitionsCompetitionIdLeaguesJoinRoute
  '/competitions/$competitionId/leagues': typeof CompetitionsCompetitionIdLeaguesIndexRoute
  '/competitions/$competitionId/matches': typeof CompetitionsCompetitionIdMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
  '/competitions/$competitionId/leaderboard': typeof CompetitionsCompetitionIdLeaderboardRoute
  '/competitions/$competitionId/': typeof CompetitionsCompetitionIdIndexRoute
  '/competitions/$competitionId/leagues/$leagueId': typeof CompetitionsCompetitionIdLeaguesLeagueIdRoute
  '/competitions/$competitionId/leagues/join': typeof CompetitionsCompetitionIdLeaguesJoinRoute
  '/competitions/$competitionId/leagues/': typeof CompetitionsCompetitionIdLeaguesIndexRoute
  '/competitions/$competitionId/matches/': typeof CompetitionsCompetitionIdMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/matches/$matchId'
    | '/competitions/'
    | '/api/auth/$'
    | '/api/cron/score'
    | '/competitions/$competitionId/leaderboard'
    | '/competitions/$competitionId/'
    | '/competitions/$competitionId/leagues/$leagueId'
    | '/competitions/$competitionId/leagues/join'
    | '/competitions/$competitionId/leagues/'
    | '/competitions/$competitionId/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/matches/$matchId'
    | '/competitions'
    | '/api/auth/$'
    | '/api/cron/score'
    | '/competitions/$competitionId/leaderboard'
    | '/competitions/$competitionId'
    | '/competitions/$competitionId/leagues/$leagueId'
    | '/competitions/$competitionId/leagues/join'
    | '/competitions/$competitionId/leagues'
    | '/competitions/$competitionId/matches'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/matches/$matchId'
    | '/competitions/'
    | '/api/auth/$'
    | '/api/cron/score'
    | '/competitions/$competitionId/leaderboard'
    | '/competitions/$competitionId/'
    | '/competitions/$competitionId/leagues/$leagueId'
    | '/competitions/$competitionId/leagues/join'
    | '/competitions/$competitionId/leagues/'
    | '/competitions/$competitionId/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronScoreRoute: typeof ApiCronScoreRoute
  CompetitionsCompetitionIdLeaderboardRoute: typeof CompetitionsCompetitionIdLeaderboardRoute
  CompetitionsCompetitionIdIndexRoute: typeof CompetitionsCompetitionIdIndexRoute
  CompetitionsCompetitionIdLeaguesLeagueIdRoute: typeof CompetitionsCompetitionIdLeaguesLeagueIdRoute
  CompetitionsCompetitionIdLeaguesJoinRoute: typeof CompetitionsCompetitionIdLeaguesJoinRoute
  CompetitionsCompetitionIdLeaguesIndexRoute: typeof CompetitionsCompetitionIdLeaguesIndexRoute
  CompetitionsCompetitionIdMatchesIndexRoute: typeof CompetitionsCompetitionIdMatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/': {
      id: '/competitions/$competitionId/'
      path: '/competitions/$competitionId'
      fullPath: '/competitions/$competitionId/'
      preLoaderRoute: typeof CompetitionsCompetitionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/leaderboard': {
      id: '/competitions/$competitionId/leaderboard'
      path: '/competitions/$competitionId/leaderboard'
      fullPath: '/competitions/$competitionId/leaderboard'
      preLoaderRoute: typeof CompetitionsCompetitionIdLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/score': {
      id: '/api/cron/score'
      path: '/api/cron/score'
      fullPath: '/api/cron/score'
      preLoaderRoute: typeof ApiCronScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/matches/': {
      id: '/competitions/$competitionId/matches/'
      path: '/competitions/$competitionId/matches'
      fullPath: '/competitions/$competitionId/matches/'
      preLoaderRoute: typeof CompetitionsCompetitionIdMatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/leagues/': {
      id: '/competitions/$competitionId/leagues/'
      path: '/competitions/$competitionId/leagues'
      fullPath: '/competitions/$competitionId/leagues/'
      preLoaderRoute: typeof CompetitionsCompetitionIdLeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/leagues/join': {
      id: '/competitions/$competitionId/leagues/join'
      path: '/competitions/$competitionId/leagues/join'
      fullPath: '/competitions/$competitionId/leagues/join'
      preLoaderRoute: typeof CompetitionsCompetitionIdLeaguesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId/leagues/$leagueId': {
      id: '/competitions/$competitionId/leagues/$leagueId'
      path: '/competitions/$competitionId/leagues/$leagueId'
      fullPath: '/competitions/$competitionId/leagues/$leagueId'
      preLoaderRoute: typeof CompetitionsCompetitionIdLeaguesLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronScoreRoute: ApiCronScoreRoute,
  CompetitionsCompetitionIdLeaderboardRoute:
    CompetitionsCompetitionIdLeaderboardRoute,
  CompetitionsCompetitionIdIndexRoute: CompetitionsCompetitionIdIndexRoute,
  CompetitionsCompetitionIdLeaguesLeagueIdRoute:
    CompetitionsCompetitionIdLeaguesLeagueIdRoute,
  CompetitionsCompetitionIdLeaguesJoinRoute:
    CompetitionsCompetitionIdLeaguesJoinRoute,
  CompetitionsCompetitionIdLeaguesIndexRoute:
    CompetitionsCompetitionIdLeaguesIndexRoute,
  CompetitionsCompetitionIdMatchesIndexRoute:
    CompetitionsCompetitionIdMatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
