/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as LeaguesIndexRouteImport } from './routes/leagues/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as LeaguesJoinRouteImport } from './routes/leagues/join'
import { Route as LeaguesLeagueIdRouteImport } from './routes/leagues/$leagueId'
import { Route as ApiCronScoreRouteImport } from './routes/api/cron/score'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesJoinRoute = LeaguesJoinRouteImport.update({
  id: '/leagues/join',
  path: '/leagues/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdRoute = LeaguesLeagueIdRouteImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScoreRoute = ApiCronScoreRouteImport.update({
  id: '/api/cron/score',
  path: '/api/cron/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/leagues': typeof LeaguesIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/score': typeof ApiCronScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/matches/$matchId'
    | '/leagues/'
    | '/matches/'
    | '/api/auth/$'
    | '/api/cron/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/matches/$matchId'
    | '/leagues'
    | '/matches'
    | '/api/auth/$'
    | '/api/cron/score'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/matches/$matchId'
    | '/leagues/'
    | '/matches/'
    | '/api/auth/$'
    | '/api/cron/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
  LeaguesJoinRoute: typeof LeaguesJoinRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronScoreRoute: typeof ApiCronScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/join': {
      id: '/leagues/join'
      path: '/leagues/join'
      fullPath: '/leagues/join'
      preLoaderRoute: typeof LeaguesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/score': {
      id: '/api/cron/score'
      path: '/api/cron/score'
      fullPath: '/api/cron/score'
      preLoaderRoute: typeof ApiCronScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
  LeaguesJoinRoute: LeaguesJoinRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronScoreRoute: ApiCronScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
